<a href="https://colab.research.google.com/github/ashish-singh79/Ashish6265.github.io/blob/main/basic_second_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.array() — Apne data se Array banana

Jab hamare paas already numbers/list ho aur usko NumPy array mein convert karna ho, tab np.array() use karte hain.**bold text**

In [ ]:
import numpy as np

In [ ]:
marks = np.array([10,20,30,40])
print(marks)

[10 20 30 40]


In [ ]:
marks = np.array([[20,40],
                  [70,45]])
print(marks)
print(marks.ndim)

[[20 40]
 [70 45]]
2


np.arange() — Range ke numbers ka Array

np.arange() se ek range ke numbers automatically generate hote hain.

In [ ]:
marks = np.arange(1,9)
print(marks)

[1 2 3 4 5 6 7 8]


In [ ]:
marks = np.arange(1,12,3)
print(marks)

[ 1  4  7 10]


np.random.randint() — Random Integer

Iska use random whole numbers generate karne ke liye hota hai.

In [ ]:
marks = np.random.randint(1,12)
print(marks)

5


In [ ]:
marks = np.random.randint(1,14,5)
print(marks)

[ 4 11 12  1  8]


np.random.uniform() — Random Decimal Numbers

randint() se whole numbers milte hain, jabki uniform() se decimal/random floating-point numbers milte hain.

In [ ]:
marks = np.random.uniform(1,11)
print(marks)

8.074903459890841


In [ ]:
marks = np.random.uniform(1,13,4)
print(marks)

[11.02593184 11.19844474  9.68174634  6.84757376]


np.linspace() — Equal Distance wale Numbers

linspace() ka use given range mein equally spaced numbers banane ke liye hota hai.

Example:

In [ ]:
marks = np.linspace(1,14)
print(marks)

[ 1.          1.26530612  1.53061224  1.79591837  2.06122449  2.32653061
  2.59183673  2.85714286  3.12244898  3.3877551   3.65306122  3.91836735
  4.18367347  4.44897959  4.71428571  4.97959184  5.24489796  5.51020408
  5.7755102   6.04081633  6.30612245  6.57142857  6.83673469  7.10204082
  7.36734694  7.63265306  7.89795918  8.16326531  8.42857143  8.69387755
  8.95918367  9.2244898   9.48979592  9.75510204 10.02040816 10.28571429
 10.55102041 10.81632653 11.08163265 11.34693878 11.6122449  11.87755102
 12.14285714 12.40816327 12.67346939 12.93877551 13.20408163 13.46938776
 13.73469388 14.        ]


In [ ]:
marks = np.linspace(1,16,3)
print(marks)

[ 1.   8.5 16. ]
