<a href="https://colab.research.google.com/github/ashish-singh79/Ashish6265.github.io/blob/main/basic_first_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# SHAPE, NDIM ,**SIZE**


In [21]:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


In [22]:
a = np.array([[1,2],
             [4,5]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 2)
2
4


In [23]:
a =np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)



[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3
9


ITEMSIZE

In [29]:
a =np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])
print(a.itemsize)

8


In [31]:
a =np.array([[1,2,3],
            [4,5,6]])
print(a.itemsize)

8


DATA **TYPE**

In [34]:
a = np.array([1,2,3])
print(a.dtype)

int64


**RESHAPE**

In [39]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]
